server:
  port: 8080
  routes:
    - path: "/api/v1"
      host: "http://127.0.0.1:3000"
      target_path: "/api/v1"
    - path: "/api/v2"
      host: "http://127.0.0.1:3000"
      target_path: "/api/v2"
add_header:
  ABC: ["abc"]
caching:
  enabled: true
  ttl: 3600
blacklist:
  - "192.168.1.101"
  - "192.168.1.102"
logger:
  level: "debug"
  file: "reverseproxy.log"