server:
  port: 8080
  routes:
    - path: "/api/v1"
      target: "http://localhost:3000/api/v1"
    - path: "/api/v2"
      target: "http://localhost:3000/api/v2"
caching:
  enabled: true
  ttl: 3600
blacklist:
  - "192.168.1.101"
  - "192.168.1.102"
logger:
  level: "debug"
  file: "reverseproxy.log"